[server]
# Set the port and address for Streamlit
port = 8501
address = "0.0.0.0"

[theme]
primaryColor = "#FBF9D1"
backgroundColor = "#FBF9D1"
secondaryBackgroundColor = "#C1856D"
textColor = "#262730"
font = "sans serif"
